using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class HUD : MonoBehaviour
{
    // ì´ì•Œ ì •ë³´ë¥¼ ì–»ê¸° ìœ„í•´ ğŸ“œGun.cs, ğŸ“œGunController.cs ê°€ í•„ìš”
    [SerializeField]
    private GunController theGunController;
    private Gun currentGun;

    // ì´ì•Œ í…ìŠ¤íŠ¸ UIë“¤ì„ ë‹´ì•˜ë˜ ì´ë¯¸ì§€ UIë¥¼ í• ë‹¹í•  ê²ƒì´ë‹¤. í•„ìš”í•  ë•Œ HUDë¥¼ í˜¸ì¶œí•˜ê³  í•„ìš” ì—†ì„ ë• ë¹„í™œì„±í™” í•  ê²ƒì´ë‹¤.
    [SerializeField]
    private GameObject go_BulletHUD;

    // ì´ì•Œ ê°œìˆ˜ë¥¼ í…ìŠ¤íŠ¸ UIì— ë°˜ì˜
    [SerializeField]
    private Text[] text_Bullet;  

    void Update()
    {
        CheckBullet();
    }

    private void CheckBullet()
    {
        currentGun = theGunController.GetGun();
        text_Bullet[0].text = currentGun.carryBulletCount.ToString();
        text_Bullet[1].text = currentGun.reloadBulletCount.ToString();
        text_Bullet[2].text = currentGun.currentBulletCount.ToString();
    }
}